### ISSUE TITLE
Feature: Support multiple dbPath's

### ISSUE THREAD

**Issue by shortdudey123** [jacksontj/gogogeo#1]
Looks like the HTTP side can handle all the different types of MaxMind GeoIP2 db's.  However, it looks like only one can actually be loaded.  You should be able to load multiple in the same process (i.e. Country and ISP)

**Comment by jacksontj** [comment]
Yea, definitely want that :) I also plan on supporting hot-reload of DBs. If you'd like you are welcome to submit a PR-- otherwise I'll get around to it eventually... maybe ;)

**Comment by shortdudey123** [comment]
Awesome!
